name: Build

on:
  push:
    branches:
      - master
  pull_request:
      types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '2.1.x'
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
      - name: Build
        env:
          TOKEN: ${{ secrets.GH_TOKEN_SCOPE_PACKAGES }}
        run: |
          dotnet tool install --global dotnet-sonarscanner --version 5.7.1
          dotnet tool install --global dotnet-coverage --version 17.3.6
          dotnet sonarscanner begin /o:"effortgames" \
                                    /k:"EffortGames_${{ github.event.repository.name }}" \
                                    /d:sonar.login="${{ secrets.SONAR_TOKEN }}" \
                                    /d:sonar.host.url="https://sonarcloud.io" \
                                    /d:sonar.cs.vscoveragexml.reportsPaths=coverage.xml
          dotnet nuget add source --username USERNAME --password "${TOKEN}" --store-password-in-clear-text --name github-effortgames "https://nuget.pkg.github.com/EffortGames/index.json"
          dotnet build .
          dotnet test .
          dotnet-coverage collect 'dotnet test' -f xml  -o 'coverage.xml'
          dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
